name: Prevent Push

on:
  push:
    branches:
      - main  # Change this to your branch name

jobs:
  prevent-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get commit message
      id: get_commit_message
      run: |
        COMMIT_MESSAGE=$(git log -n 1 --pretty=format:"%s")
        echo "::set-output name=commit_message::${COMMIT_MESSAGE}"

    - name: Run pre-push hook
      run: |
        # Access the commit message using the output variable
        COMMIT_MESSAGE="${{ steps.get_commit_message.outputs.commit_message }}"

        # Add your condition to prevent the push
        if [ "$COMMIT_MESSAGE" == "YOUR_UNWANTED_COMMIT_MESSAGE" ]; then
          echo "Error: Push rejected. This commit message is not allowed."
          exit 1
        fi
      shell: bash
